name: yashwanth 

on:
 workflow_dispatch:
 
jobs: 
 build:
  runs-on: ubuntu-latest
  steps:
  
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
             fetch-depth: 1
             ref: main
 
     - name: List files
       run: ls -lr
       
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: yashu901
          password: ${{ secrets.DOCKERHUB }}

     - name: Build Docker image
       run: |
             docker build -t yashu901/tutorial:latest .
             docker tag yashu901/tutorial:latest 
             

