name: yashwanth 

on:
 workflow_dispatch:
 
jobs: 
 clone:
  runs-on: ubuntu-latest
  steps:
  
     - name: Checkout my repository
       uses: actions/checkout@v4
 
     - name: List files
       run: ls 
